config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :approvers, path: 'approver'
  devise_for :authors, path: 'author'
  devise_for :admins, path: 'admin'

  get '/logout', to: 'application#logout', as: :logout
  get '/about', to: 'application#about', as: :about_page
  get '/main', to: 'application#main', as: :main_page
  get '/docs', to: 'application#docs', as: :docs_page

  authenticate :author do
    get '/login', to: 'application#login', as: :login
  end

  get '/', to: redirect(path: '/main')

  mount Sidekiq::Web => '/sidekiq'

  mount OkComputer::Engine, at: "/healthcheck"

  ## works: get '/committee_members/autocomplete', to: 'ldap_lookup#autocomplete', as: :committee_members_autocomplete
  get '/committee_members/autocomplete', to: 'application#autocomplete', as: :committee_members_autocomplete

  get '/special_committee/:authentication_token', to: 'special_committee#main', as: :special_committee_main

  post '/special_committee/:authentication_token/advance_to_reviews', to: 'special_committee#advance_to_reviews', as: :advance_to_reviews

  post 'email_contact_form', to: 'email_contact_form#create', as: :email_contact_form_index
  get 'email_contact_form', to: 'email_contact_form#new', as: :email_contact_form_new

  namespace :admin do
    resources :admins, except: [:index, :show]
    resources :degrees, except: [:show, :destroy]
    resources :programs, except: [:show, :destroy]
    resources :approval_configurations, except: [:new, :create, :destroy]
    resources :authors,  except: [:new, :create, :show, :destroy]

    get '/custom_report', to: 'reports#custom_report_index', as: :custom_report_index
    patch '/custom_report_export', to: 'reports#custom_report_export', defaults: { format: 'csv' }, as: :custom_report_export
    get '/committee_report', to: 'reports#committee_report_index', as: :committee_report_index
    patch '/committee_report_export', to: 'reports#committee_report_export', defaults: { format: 'csv' }, as: :committee_report_export
    get '/confidential_hold_report', to: 'reports#confidential_hold_report_index', as: :confidential_hold_report_index
    patch '/confidential_hold_report_export', to: 'reports#confidential_hold_report_export', defaults: { format: 'csv' }, as: :confidential_hold_report_export

    get '/authors/contact_list', to: 'authors#email_contact_list', as: :email_contact_list

    get '/submissions/:id/edit', to: 'submissions#edit', as: :edit_submission
    delete '/submissions', to: 'submissions#bulk_destroy', as: :delete_submissions

    patch '/submissions/:id/format_review_response', to: 'submissions#record_format_review_response', as: :submissions_format_review_response
    patch '/submissions/:id/final_submission_pending_response', to: 'submissions#record_final_submission_pending_response', as: :submissions_final_submission_pending_response
    patch '/submissions/:id/update_final_submission', to: 'submissions#record_send_back_to_final_submission', as: :submissions_update_final_submission
    patch '/submissions/:id/final_submission_response', to: 'submissions#record_final_submission_response', as: :submissions_final_submission_response
    patch '/submissions/:id/update_released', to: 'submissions#update_released', as: :submissions_update_released
    patch '/submissions/:id/update_waiting_to_be_released', to: 'submissions#update_waiting_to_be_released', as: :submissions_update_waiting_to_be_released
    patch '/submissions/:id', to: 'submissions#update', as: :submission
    get '/submissions/:id/audit', to: 'submissions#audit', as: :submission_audit
    get '/submissions/:id/committee_members_refresh', to: 'submissions#refresh_committee', as: :refresh_committee

    get '/:degree_type', to: 'submissions#dashboard', as: :submissions_dashboard
    get '/:degree_type/:scope', to: 'submissions#index', as: :submissions_index

    get '/submissions/:id/print_signatory_page', to: 'submissions#print_signatory_page', as: :submission_print_signatory_page
    patch '/submissions/:id/print_signatory_page_update', to: 'submissions#print_signatory_page_update', as: :submissions_print_signatory_page_update

    patch '/:degree_type/final_submission_approved', to: 'submissions#release_for_publication', as: :submissions_release_final_submission_approved
    patch '/:degree_type/extend_publication_date', to: 'submissions#extend_publication_date', as: :submissions_extend_publication_date

    patch '/:degree_type/export_final_submission_approved', to: 'reports#final_submission_approved', as: :export_final_submission_approved

    get 'submissions/:id/academic_plan_refresh', to: 'submissions#refresh_academic_plan', as: 'submissions_refresh_academic_plan'

    post 'submissions/:id/send_email_reminder', to: 'submissions#send_email_reminder', as: 'submissions_send_email_reminder'

    get '/files/format_reviews/:id',    to: 'files#download_format_review',    as: :format_review_file
    get '/files/final_submissions/:id', to: 'files#download_final_submission', as: :final_submission_file

    root to: 'submissions#redirect_to_default_dashboard'
  end

  namespace :author do
    resources :authors, except: [:index, :show, :destroy]
    resources :submissions, except: [:show] do
      get '/program_information', to: 'submissions#program_information', as: :program_information
      get '/academic_plan_refresh', to: 'submissions#refresh', as: :refresh

      get '/format_review', to: 'submission_format_review#show', as: :format_review
      get '/format_review/edit', to: 'submission_format_review#edit', as: :edit_format_review
      patch '/format_review', to: 'submission_format_review#update', as: :update_format_review

      get '/final_submission', to: 'submissions#final_submission', as: :final_submission
      get '/final_submission/edit', to: 'submissions#edit_final_submission', as: :edit_final_submission
      patch '/final_submission', to: 'submissions#update_final_submission', as: :update_final_submission
      get '/date_defended_refresh', to: 'submissions#refresh_date_defended', as: :refresh_date_defended

      resource :committee_members, shallow: true # We only modify the set of committee members en masse
      get '/committee_members_refresh', to: 'committee_members#refresh', as: :refresh_committee

      post '/send_email_reminder', to: 'submissions#send_email_reminder'

      get '/committee_review', to: 'submissions#committee_review', as: :committee_review
    end
    get '/published_submissions', to: 'submissions#published_submissions_index', as: :published_submissions_index

    get '/files/format_reviews/:id',    to: 'files#download_format_review',    as: :format_review_file
    get '/files/final_submissions/:id', to: 'files#download_final_submission', as: :final_submission_file

    root to: 'submissions#index'
    get '/tips', to: 'authors#technical_tips', as: :technical_tips
  end

  namespace :approver do
    get '/reviews', to: 'approvers#index', as: :approver_reviews
    get '/committee_member/:id', to: 'approvers#edit'
    patch '/committee_member/:id', to: 'approvers#update', as: :update_committee_member
    get '/special_committee_link/:authentication_token', to: 'approvers#special_committee_link', as: :special_committee_link
    get '/committee_member/:id/committee_reviews', to: 'approvers#committee_reviews', as: :committee_reviews
    get '/files/final_submissions/:id', to: 'approvers#download_final_submission', as: :approver_file
    root to: 'approvers#index'
  end

  root to: 'application#main'
  match "/404", to: 'errors#render_404', via: :all
  match "/500", to: 'errors#render_500', via: :all
  match "/401", to: 'errors#render_401', via: :all
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/shared/_admin_support_link.html.erb
<%= link_to 'Contact Support', "mailto:#{I18n.t('service_desk_email_address')}", class: 'small' %><span class="sr-only">opens mail to <%= I18n.t('service_desk_email_address').to_s %></span>

app/views/shared/_ask_link.html.erb
<%= link_to 'Please direct questions to Ask!', t('libraries_help_link'), class: 'small', target: '_blank' %><span class="sr-only">link opens in a new tab</span>

app/views/shared/_copyright_statement.html.erb
<div tabindex="0">
<br />
<strong>Copyright Statement</strong>
<p>I hereby certify that this <%= I18n.t("#{current_partner.id}.submission.descriptor") %> is my original work. To the extent that this document contains any materials that are not my original work, I have obtained all necessary permissions for copyrighted material included in my <%= I18n.t("#{current_partner.id}.submission.descriptor") %>.  I certify that the version I am submitting is the same as that was authorized for submission by the committee.  I hereby grant to The Pennsylvania State University and its authorized service providers an irrevocable and perpetual non-exclusive license to make available to the public and archive my thesis or dissertation in whole or in part in all forms of media, now or hereafter known.  Except for the forgoing license I retain all ownership rights to the copyright of the thesis or dissertation. I also retain the right to use in future works (such as articles or books) all or part of this <%= I18n.t("#{current_partner.id}.submission.descriptor") %>.
</p>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="row">
    <div class="col-xs-12">
      <div class="alert alert-danger" role="alert" aria-labelledby="alert-message">
        <ul>
          <% for message in object.errors.values %>
            <li><%= message.first %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_federal_funding_checkbox.html.erb
<div tabindex="0">
<br />
<strong>Federal Funding Statement</strong>
<p><%= f.input :federal_funding, as: :radio_buttons,
               label: false, wrapper: :vertical_radio_and_checkboxes,
               required: true,
               collection: [["I confirm that, as required by federal guidelines, all federal funds
                              used for the work described in this #{f.object.degree_type.to_s}
                              have been explicitly acknowledged in the document, along with a disclaimer
                              indicating that the findings and conclusions do not necessarily reflect the
                              view of the funding agency. [Please see the Research Terms Clarification to
                              2CFR § 200.328 (pp. 20-21) for the precise language to be used.]", true],
                              ['I confirm that no federal funds were used for the work described in this
                              dissertation.',false]]%>
</div>

app/views/shared/_file_fields.html.erb
<div class="nested-fields col-sm-8">
  <% if file_fields.object.asset_identifier %>
    <div id="<%= file_fields.object.class_name %>-<%= file_fields.object.id %>" class="form-group uploaded-file-link <%= can_delete ? 'can-delete' : 'cannot-delete' %> ">
        <%= link_to_remove_association "[delete]", file_fields, id: 'file_delete_link', class: 'text-danger can-toggle-clickability' %>
            <%= link_to "/#{session['user_role']}/files/#{file_fields.object.link_identifier}/#{file_fields.object.id}", class: 'file-link', target: '_blank' do %>
                <%= file_fields.object.asset_identifier %>
            <% end %>
      <div class="badge badge-secondary float-right upload-date"><div>Uploaded <%= l file_fields.object.created_at, format: t("#{current_partner.id}.time.formats.medium") %></div></div>
    </div>
  <% else %>
    <span class='sr-only'>Select the file you wish to upload using the file browser.</span>
      <%= file_fields.input :asset, as: :file, label: false %>
      <%= link_to_remove_association "[remove]", file_fields, class: 'text-danger can-toggle-clickability', html: {tabindex: '0'}  %>
      <%= file_fields.input :asset_cache, :as => :hidden %>
      <%= file_fields.object.asset_identifier %>
  <% end %>
</div>

app/views/shared/_final_submission_confidential_hold_checkbox.erb
<%= render partial: 'shared/release_statement', f: f %>
<%= f.input :has_agreed_to_publication_release, label: 'I agree to the publication release agreement', as: :boolean, wrapper: :vertical_boolean, required: true %>

app/views/shared/_flash_messages.html.erb
<div class="row">
  <%= render '/flash_msg', layout: 'shared/flash_message' %>
</div>

app/views/shared/_header.html.erb
<header class="<%= page_classes %>" >
  <div class="container-fluid">
    <div id="shield-and-logo" class="row">
      <div class="col-sm-1">
        <a id="psu-shield" href="http://libraries.psu.edu/">
          <%= image_tag("#{asset_pack_path 'media/images/PS_UL_REV_RGB_2C.png'}", alt: "PSU Libraries logo", width: '120', height: '55' ) %>
        </a>
      </div>
      <div id="logo-old" class="col-sm-8">
        <a href="/"><%=
        if current_partner.graduate?
          "Electronic Theses and Dissertations for The Graduate School"
        elsif current_partner.honors?
          "Electronic Honors Theses for The Schreyer's Honors College"
        elsif current_partner.milsch?
          "Electronic Theses for The Millennium Scholars Program"
        elsif current_partner.sset?
          "World Campus Electronic Final Papers for The School of Science, Engineering, and Technology"
        end %>
            </a>
      </div>
    </div>
  </div>
  <%= render partial: '/matomo_analytics' if ENV['HOSTNAME'] == 'etdaworkflow1prod' %>
  <%= render partial: 'shared/nav_bar' %>
</header>

app/views/shared/_keyword_fields.html.erb
<div class="nested-fields">
  <%= keyword_fields.input :word, input_html: { class: 'keyword-word' }, as: :text, label: false  %>
  <%= link_to_remove_association "[remove]", keyword_fields, class: 'text-danger can-toggle-clickability' %>
</div>

app/views/shared/_nav_bar.html.erb
<nav id="account-navigation" class="navbar navbar-default" role="navigation" aria-labelledby="top-navigation">
  <div id=top-navigation class="col-sm-6">
    <ul class="list-inline navbar-list">
      <li class= "<%= top_nav_active?('main') %>">
        <%= link_to 'Home', main_page_path, class: 'btn btn-sm navbar-btn' %>
      </li>
      <li class="<%= top_nav_active?('about') %>">
        <%= link_to 'About', about_page_path, class: 'btn btn-sm navbar-btn' %>
      </li >
      <% if session[:user_role] == 'author' || session[:user_role] == 'approver' %>
        <li class="<%= top_nav_active?('email') %>">
          <%= link_to 'Contact Us', email_contact_form_new_path, class: 'btn btn-sm navbar-btn ' %>
        </li>
      <% end %>
      <% unless (controller_name == 'application' && action_name == 'main') || current_partner.sset? %>
        <li>
          <%= link_to 'Explore', EtdUrls.new.explore, class: 'btn btn-sm navbar-btn' %>
        </li>
      <% end  %>
    </ul>
  </div>


  <div class="log-div">
    <% unless controller_name == 'special_committee' %>
      <% unless @current_remote_user || author_signed_in? || admin_signed_in? || approver_signed_in? %>
        <%= link_to 'Log In', :login, class: "btn btn-sm navbar-btn" %>
      <% else %>
        <span class="navbar-text small hidden-xs">Logged in as <%= session[:user_name] || current_author.access_id %></span>
        <%= link_to 'Log Out', :logout, class: "btn btn-sm navbar-btn" %>
      <% end %>
    <% end %>
  </div>
</nav>

app/views/shared/_proquest_agreement.html.erb
<div tabindex="0">
  <br />
  <strong>ProQuest Statement</strong>
  <p>The Pennsylvania State University disseminates its doctoral dissertations in ProQuest Dissertation & Theses Global in order to promote and preserve the intellectual output of its doctoral degree candidates. ProQuest Dissertation & Theses Global reaches 3,100 universities with over 200 million searches annually and supports discovery of scholarly output through many major subject and discipline indexes (MathSciNet, PsycINFO, ERIC, etc.). ProQuest provides these dissemination services at no charge.</p>
  <p>ProQuest facilitates the nonexclusive distribution of your doctoral dissertation. You are eligible for a 10% royalty based upon sales and usage of the full text of your work distributed by ProQuest. You may withdraw your work from distribution at any time. Further author agreement information can be found here: <a target="_blank" href='https://media2.proquest.com/documents/pqdt-authoragreement_0.pdf'>pqdt-authoragreement_0.pdf</a>)</p>
  <p>Please contact disspub@proquest.com with any questions or to set up your account to collect royalties.</p>
</div>

app/views/shared/_release_statement.html.erb
<div tabindex="0">
  <br />
  <strong>Publication Release Agreement</strong>
  <p>By checking this box, I agree to release my <%= @submission.degree_type.name.downcase %> for publication and understand that my name will be included in publication.
  </p>
</div>

app/views/shared/_site_footer.html.erb
<footer>
  <div id="courtesy-navigation" class="navbar navbar-default">
    <div class="container-fluid">
      <ul class="nav navbar-list">
        <li><a id="psu-shield" href="http://psu.edu/"><%= image_tag("#{asset_pack_path 'media/images/PS_HOR_REV_RGB_2C.png'}", alt: "PSU Libraries logo", width: '100', height: '45' ) %></a></li>
        <li class="text"><%= link_to t("#{current_partner.id}.partner.name"), t("#{current_partner.id}.partner.url"), class: 'small', target: '_blank', aria: {label: "link opens in a new tab" } %></li>
        <li class="text"><%= link_to "© #{Time.now.year} The Pennsylvania State University", 'http://www.psu.edu/ur/copyright.html', class: 'small', target: '_blank', aria: {label: "link opens in a new tab" } %></li>
        <li class="text"><%= link_to 'Privacy and Legal Statements', 'http://www.psu.edu/ur/legal.html', class: 'small', target: '_blank', aria: {label: "link opens in a new tab" } %></li>
        <li class="text"><%= link_to 'Accessibility', 'https://www.psu.edu/accessibilitystatement', class: 'small', target: '_blank', aria: {label: "link opens in a new tab" } %></li>
        <li class="text"><%= render_conditional_links %></li>
      </ul>
      <p class="small version text"><span><%= current_version_number %></span></p>
    </div>
  </div>
</footer>