config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :approvers, path: 'approver'
  devise_for :authors, path: 'author'
  devise_for :admins, path: 'admin'

  get '/logout', to: 'application#logout', as: :logout
  get '/about', to: 'application#about', as: :about_page
  get '/main', to: 'application#main', as: :main_page
  get '/docs', to: 'application#docs', as: :docs_page

  authenticate :author do
    get '/login', to: 'application#login', as: :login
  end

  get '/', to: redirect(path: '/main')

  mount Sidekiq::Web => '/sidekiq'

  mount OkComputer::Engine, at: "/healthcheck"

  ## works: get '/committee_members/autocomplete', to: 'ldap_lookup#autocomplete', as: :committee_members_autocomplete
  get '/committee_members/autocomplete', to: 'application#autocomplete', as: :committee_members_autocomplete

  get '/special_committee/:authentication_token', to: 'special_committee#main', as: :special_committee_main

  post '/special_committee/:authentication_token/advance_to_reviews', to: 'special_committee#advance_to_reviews', as: :advance_to_reviews

  post 'email_contact_form', to: 'email_contact_form#create', as: :email_contact_form_index
  get 'email_contact_form', to: 'email_contact_form#new', as: :email_contact_form_new

  namespace :admin do
    resources :admins, except: [:index, :show]
    resources :degrees, except: [:show, :destroy]
    resources :programs, except: [:show, :destroy]
    resources :approval_configurations, except: [:new, :create, :destroy]
    resources :authors,  except: [:new, :create, :show, :destroy]

    get '/custom_report', to: 'reports#custom_report_index', as: :custom_report_index
    patch '/custom_report_export', to: 'reports#custom_report_export', defaults: { format: 'csv' }, as: :custom_report_export
    get '/committee_report', to: 'reports#committee_report_index', as: :committee_report_index
    patch '/committee_report_export', to: 'reports#committee_report_export', defaults: { format: 'csv' }, as: :committee_report_export
    get '/confidential_hold_report', to: 'reports#confidential_hold_report_index', as: :confidential_hold_report_index
    patch '/confidential_hold_report_export', to: 'reports#confidential_hold_report_export', defaults: { format: 'csv' }, as: :confidential_hold_report_export

    get '/authors/contact_list', to: 'authors#email_contact_list', as: :email_contact_list

    get '/submissions/:id/edit', to: 'submissions#edit', as: :edit_submission
    delete '/submissions', to: 'submissions#bulk_destroy', as: :delete_submissions

    patch '/submissions/:id/format_review_response', to: 'submissions#record_format_review_response', as: :submissions_format_review_response
    patch '/submissions/:id/final_submission_pending_response', to: 'submissions#record_final_submission_pending_response', as: :submissions_final_submission_pending_response
    patch '/submissions/:id/update_final_submission', to: 'submissions#record_send_back_to_final_submission', as: :submissions_update_final_submission
    patch '/submissions/:id/final_submission_response', to: 'submissions#record_final_submission_response', as: :submissions_final_submission_response
    patch '/submissions/:id/update_released', to: 'submissions#update_released', as: :submissions_update_released
    patch '/submissions/:id/update_waiting_to_be_released', to: 'submissions#update_waiting_to_be_released', as: :submissions_update_waiting_to_be_released
    patch '/submissions/:id', to: 'submissions#update', as: :submission
    get '/submissions/:id/audit', to: 'submissions#audit', as: :submission_audit
    get '/submissions/:id/committee_members_refresh', to: 'submissions#refresh_committee', as: :refresh_committee

    get '/:degree_type', to: 'submissions#dashboard', as: :submissions_dashboard
    get '/:degree_type/:scope', to: 'submissions#index', as: :submissions_index

    get '/submissions/:id/print_signatory_page', to: 'submissions#print_signatory_page', as: :submission_print_signatory_page
    patch '/submissions/:id/print_signatory_page_update', to: 'submissions#print_signatory_page_update', as: :submissions_print_signatory_page_update

    patch '/:degree_type/final_submission_approved', to: 'submissions#release_for_publication', as: :submissions_release_final_submission_approved
    patch '/:degree_type/extend_publication_date', to: 'submissions#extend_publication_date', as: :submissions_extend_publication_date

    patch '/:degree_type/export_final_submission_approved', to: 'reports#final_submission_approved', as: :export_final_submission_approved

    get 'submissions/:id/academic_plan_refresh', to: 'submissions#refresh_academic_plan', as: 'submissions_refresh_academic_plan'

    post 'submissions/:id/send_email_reminder', to: 'submissions#send_email_reminder', as: 'submissions_send_email_reminder'

    get '/files/format_reviews/:id',    to: 'files#download_format_review',    as: :format_review_file
    get '/files/final_submissions/:id', to: 'files#download_final_submission', as: :final_submission_file

    root to: 'submissions#redirect_to_default_dashboard'
  end

  namespace :author do
    resources :authors, except: [:index, :show, :destroy]
    resources :submissions, except: [:show] do
      get '/program_information', to: 'submissions#program_information', as: :program_information
      get '/academic_plan_refresh', to: 'submissions#refresh', as: :refresh

      get '/format_review', to: 'submission_format_review#show', as: :format_review
      get '/format_review/edit', to: 'submission_format_review#edit', as: :edit_format_review
      patch '/format_review', to: 'submission_format_review#update', as: :update_format_review

      get '/final_submission', to: 'submissions#final_submission', as: :final_submission
      get '/final_submission/edit', to: 'submissions#edit_final_submission', as: :edit_final_submission
      patch '/final_submission', to: 'submissions#update_final_submission', as: :update_final_submission
      get '/date_defended_refresh', to: 'submissions#refresh_date_defended', as: :refresh_date_defended

      resource :committee_members, shallow: true # We only modify the set of committee members en masse
      get '/committee_members_refresh', to: 'committee_members#refresh', as: :refresh_committee

      post '/send_email_reminder', to: 'submissions#send_email_reminder'

      get '/committee_review', to: 'submissions#committee_review', as: :committee_review
    end
    get '/published_submissions', to: 'submissions#published_submissions_index', as: :published_submissions_index

    get '/files/format_reviews/:id',    to: 'files#download_format_review',    as: :format_review_file
    get '/files/final_submissions/:id', to: 'files#download_final_submission', as: :final_submission_file

    root to: 'submissions#index'
    get '/tips', to: 'authors#technical_tips', as: :technical_tips
  end

  namespace :approver do
    get '/reviews', to: 'approvers#index', as: :approver_reviews
    get '/committee_member/:id', to: 'approvers#edit'
    patch '/committee_member/:id', to: 'approvers#update', as: :update_committee_member
    get '/special_committee_link/:authentication_token', to: 'approvers#special_committee_link', as: :special_committee_link
    get '/committee_member/:id/committee_reviews', to: 'approvers#committee_reviews', as: :committee_reviews
    get '/files/final_submissions/:id', to: 'approvers#download_final_submission', as: :approver_file
    root to: 'approvers#index'
  end

  root to: 'application#main'
  match "/404", to: 'errors#render_404', via: :all
  match "/500", to: 'errors#render_500', via: :all
  match "/401", to: 'errors#render_401', via: :all
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/controllers/admin/submissions_controller.rb
class Admin::SubmissionsController < AdminController
  skip_before_action :verify_authenticity_token, only: [:send_email_reminder]
  include ActionView::Helpers::UrlHelper

  def redirect_to_default_dashboard
    redirect_to admin_submissions_dashboard_path(DegreeType.default)
  end

  def dashboard
    # Reset session semester to nil when returning to dashboard
    session[:semester] = nil
    degree_type = params[:degree_type] || DegreeType.default
    @view = Admin::SubmissionsDashboardView.new(degree_type)
  end

  def edit
    @submission = Submission.find(params[:id])
    @view = Admin::SubmissionFormView.new(@submission, session)
  end

  def update
    @submission = Submission.find(params[:id])
    if @submission.status_behavior.beyond_collecting_format_review_files? && @submission.status != 'format review completed'
      submission_update_service = FinalSubmissionUpdateService.new(params, @submission, current_remote_user)
    else
      submission_update_service = FormatReviewUpdateService.new(params, @submission, current_remote_user)
    end
    response = submission_update_service.update_record
    flash[:notice] = response[:msg]
    redirect_to response[:redirect_path]
  rescue ActiveRecord::RecordInvalid
    @view = Admin::SubmissionFormView.new(@submission, session)
    render :edit
  rescue SubmissionStatusGiver::InvalidTransition
    redirect_to session.delete(:return_to)
    flash[:alert] = 'Oops! You may have submitted invalid format review data. Please check that the submission\'s format review information is correct.'
  end

  def index
    session[:return_to] = request.referer
    @view = Admin::SubmissionsIndexView.new(params[:degree_type], params[:scope], view_context, session[:semester])
  end

  def audit
    @submission = Submission.find(params[:id])
    @author = @submission.author
    @most_relevant_file_links = most_relevant_file_links
  end

  def bulk_destroy
    # return_path = request.referer
    ids = params[:submission_ids].split(',')
    ids.each do |id|
      submission = Submission.find(id)
      submission.author_edit = false
      submission&.destroy
    end
    flash[:notice] = 'Submissions deleted successfully'
    redirect_to Rails.application.routes.url_helpers.admin_root_path
  rescue StandardError
    flash[:alert] = 'There was a problem deleting your submissions'
    redirect_to return_path
  end

  def release_for_publication
    ids = params[:submission_ids].split(',')
    results = Submission.release_for_publication(ids, Date.strptime(params[:date_to_release], '%m/%d/%Y'), params[:release_type])
    # error = results[1] *****MUST DISPLAY ERRORS
    flash[:notice] = results[0]
    render 'admin/submissions/publication_release_results', locals: { results: results[1] }
    # redirect_to admin_submissions_dashboard_path(params[:degree_type])
  rescue SubmissionStatusGiver::AccessForbidden
    flash[:alert] = 'There was a problem releasing the submissions, please try again.'
    redirect_to session.delete(:return_to)
  rescue SubmissionStatusGiver::InvalidTransition
    redirect_to session.delete(:return_to)
    flash[:alert] = 'Oops! You may have submitted invalid format review data. Please check that the submission\'s format review information is correct.'
  end

  def extend_publication_date
    session[:return_to] = request.referer
    ids = params[:submission_ids].split(',')
    new_date = Date.strptime(params[:date_to_release], '%m/%d/%Y')
    Submission.extend_publication_date(ids, new_date)
    flash[:notice] = "Submission publication dates have been extended until #{new_date}"
    redirect_to session.delete(:return_to) unless Rails.env.test?
  end

  def record_format_review_response
    @submission = Submission.find(params[:id])
    format_review_update_service = FormatReviewUpdateService.new(params, @submission, current_remote_user)
    response = format_review_update_service.respond_format_review
    redirect_to response[:redirect_path]
    flash[:notice] = response[:msg]
  rescue ActiveRecord::RecordInvalid
    @view = Admin::SubmissionFormView.new(@submission, session)
    render :edit
  rescue SubmissionStatusGiver::AccessForbidden
    redirect_to session.delete(:return_to)
    flash[:alert] = 'This submission\'s format review information has already been evaluated.'
  rescue SubmissionStatusGiver::InvalidTransition
    redirect_to session.delete(:return_to)
    flash[:alert] = 'Oops! You may have submitted invalid format review data. Please check that the submission\'s format review information is correct.'
  end

  def update_final_submission
    @submission = Submission.find(params[:id])
    update_service = FinalSubmissionUpdateService.new(params, @submission, current_remote_user)
    response = update_service.waiting_for_final_submission
    redirect_to response[:redirect_path]
    flash[:notice] = response[:msg]
  rescue ActiveRecord::RecordInvalid
    @view = Admin::SubmissionFormView.new(@submission, session)
    render :edit
  rescue SubmissionStatusGiver::AccessForbidden
    redirect_to session.delete(:return_to)
    flash[:alert] = 'This submission\'s final submission information has already been evaluated.'
  rescue SubmissionStatusGiver::InvalidTransition
    redirect_to session.delete(:return_to)
    flash[:alert] = 'Oops! You may have submitted invalid final submission data. Please check that the submission\'s final submission information is correct.'
  end

  def record_final_submission_pending_response
    @submission = Submission.find(params[:id])
    update_service = FinalSubmissionPendingService.new(@submission, params, current_remote_user)
    response = update_service.respond
    redirect_to response[:redirect_to]
    flash[:notice] = response[:msg]
  rescue ActiveRecord::RecordInvalid
    @view = Admin::SubmissionFormView.new(@submission, session)
    render :edit
  rescue SubmissionStatusGiver::AccessForbidden
    redirect_to session.delete(:return_to)
    flash[:alert] = 'This submission\'s final submission information has already been evaluated.'
  rescue SubmissionStatusGiver::InvalidTransition
    redirect_to session.delete(:return_to)
    flash[:alert] = 'Oops! You may have submitted invalid final submission data. Please check that the submission\'s final submission information is correct.'
  end

  def record_final_submission_response
    @submission = Submission.find(params[:id])
    update_service = FinalSubmissionUpdateService.new(params, @submission, current_remote_user)
    response = update_service.respond_final_submission
    redirect_to response[:redirect_path]
    flash[:notice] = response[:msg]
  rescue ActiveRecord::RecordInvalid
    @view = Admin::SubmissionFormView.new(@submission, session)
    render :edit
  rescue SubmissionStatusGiver::AccessForbidden
    redirect_to session.delete(:return_to)
    flash[:alert] = 'This submission\'s final submission information has already been evaluated.'
  rescue SubmissionStatusGiver::InvalidTransition
    redirect_to session.delete(:return_to)
    flash[:alert] = 'Oops! You may have submitted invalid final submission data. Please check that the submission\'s final submission information is correct.'
  end

  def update_waiting_to_be_released
    @submission = Submission.find(params[:id])
    released_submission_service = FinalSubmissionUpdateService.new(params, @submission, current_remote_user)
    response = released_submission_service.respond_waiting_to_be_released
    flash[:notice] = response[:msg]
    redirect_to response[:redirect_path]
  rescue ActiveRecord::RecordInvalid
    @view = Admin::SubmissionFormView.new(@submission, session)
    render :edit
  rescue SubmissionStatusGiver::AccessForbidden
    redirect_to session.delete(:return_to)
    flash[:alert] = 'Submission is invalid'
  rescue SubmissionStatusGiver::InvalidTransition
    redirect_to session.delete(:return_to)
    flash[:alert] = 'Oops! You may have submitted invalid format review data. Please check that the submission\'s format review information is correct.'
  end

  def update_released
    @submission = Submission.find(params[:id])
    session[:return_to] = "/admin/#{@submission.degree_type.slug}"
    released_submission_service = FinalSubmissionUpdateService.new(params, @submission, current_remote_user)
    response = released_submission_service.respond_released_submission
    flash[:notice] = response[:msg]
    redirect_to response[:redirect_path]
  rescue ActiveRecord::RecordInvalid
    @view = Admin::SubmissionFormView.new(@submission, session)
    render :edit
  rescue SubmissionStatusGiver::AccessForbidden
    redirect_to session.delete(:return_to)
    flash[:alert] = 'Submission is invalid'
  rescue SubmissionStatusGiver::InvalidTransition
    redirect_to session.delete(:return_to)
    flash[:alert] = 'Oops! You may have submitted invalid format review data. Please check that the submission\'s format review information is correct.'
  end

  def print_signatory_page
    return if params[:id].nil?

    @submission = Submission.find(params[:id])
    author = Author.find(@submission.author_id)
    @view = Admin::SignatoryPageView.new(author)
    return if author.nil?

    render 'admin/submissions/print/signatory_page', target: :blank, locals: { submission: @submission, author: author }
  end

  def print_signatory_page_update
    return if params[:id].nil?

    @submission = Submission.find(params[:id])
    @submission.update! is_printed: 1 unless @submission.is_printed?
    redirect_to admin_submissions_index_path(@submission.degree_type.slug, 'format_review_submitted')
    flash[:notice] = "Printed submission information for #{@submission.author.first_name} #{@submission.author.last_name}"
  end

  def send_email_reminder
    fail_message = 'Email was not sent. Email reminders may only be sent once a day; a reminder was recently sent to this committee member.'.html_safe
    success_message = 'Email successfully sent.'.html_safe
    @submission = Submission.find(params[:id])

app/views/admin/submissions/print/_signatory_page_bottom.html.erb
<div>
  <ul>
    <li class='col-left'><span class='print-label'><strong><u>FORMAT REVIEW</u></strong></span></li>
    <li class='col-right'><span class='print-label'><strong><u>FINAL SUBMISSION</u></strong></span></li>
  </ul>
  <br /><br />
  <ul>
    <li class='col-left'><span class='print-label'>EXCEL</span><span class='empty-underline'></span></li>
    <li class='col-right'><span class='print-label'>INTENT</span><span class='empty-underline'></span></li>
  </ul>
  <ul>
    <li class='col-left'><span class='print-label'>LIONPATH</span><span class='empty-underline'></span></li>
    <li class='col-right'><span class='print-label'>FEE</span><span class='empty-underline'></span></li>
  </ul>
  <ul>
    <li class='col-left'><span class='print-label'>REVIEW DATE</span><span class='empty-underline'></span></li>
    <li class='col-right'><span class='print-label'>EXCEL</span><span class='empty-underline'></span></li>
  </ul>
  <ul>
    <li class='col-left'>&nbsp;</li>
    <li class='col-right'><span class='print-label'>LIONPATH</span><span class='empty-underline'></span></li>
  </ul>
  <ul>
    <li class='col-left'><span class='print-label'>INTENT</span><span class='empty-underline'></span></li>
    <li class='col-right'><span class='print-label'>OTD APPROVAL DATE</span><span class='empty-underline'></span></li>
  </ul>
  <ul>
    <li class='col-left'>&nbsp;</li>
    <li class='col-right'><span class='print-label'>COMMITTEE APPROVAL DATE</span><span class='empty-underline'></span></li>
  </ul>
  <ul>
    <li class='col-left'>&nbsp;</li>
    <li class='col-right'><span class='print-label'>OPTION &nbsp; 1 &nbsp;&nbsp; 2 &nbsp;&nbsp; 3 &nbsp;&nbsp;</span></li>
  </ul>
  <ul>
    <li class='col-left'>&nbsp;</li>
    <li class='col-right'><span class='print-label'>FEDERAL FUNDING &nbsp;&nbsp; YES / NO</span></li>
  </ul>
  <ul>
    <li class='col-left'><span class='print-label'>NOTES</span></li>
  </ul>
</div>

app/views/admin/submissions/print/_signatory_page_top.html.erb
<h2>Format Review - Submission Information</h2>
<br/>
<div>
<ul>
  <li class='col-left'><span class='print-label'>Mr / Ms</span><u><%= author.last_name %>, <%= author.first_name %></u></li>
  <li class='col-right'><span class='print-label'>Date</span><u><%= submission.format_review_files_uploaded_at.strftime('%B %-e, %Y') unless submission.format_review_files_uploaded_at.nil? %></u></li>
</ul>
<ul>
  <li class='col-left'><span class='print-label'>Student ID</span><u><%= author.psu_id_number(author.access_id) %></u></li>
  <li class='col-right'><span class='print-label'>Phone</span><u><%= author.phone_number %></u></li>
</ul>
<ul>
  <li class='col-left'><span class='print-label'>E-Mail</span><u><%= author.psu_email_address %></u></li>
  <li class='col-right'><span class='print-label'>Alt Email</span><u><%= author.alternate_email_address %></u></li>
</ul>
<ul>
  <li class='col-left'><span class='print-label'>Address</span><u><%= @view.address_line1 %></u></li>
  <li class='col-right'><br /></li>
</ul>
<ul>
  <li class='col-left'><u><%= @view.address_line2 %></u></li>
</ul>
<ul>
  <li class='col-left'><span class='print-label'>Semester intending to graduate</span><u><%= submission.preferred_semester %>
    - <%= submission.preferred_year %></u></li>
</ul>
<ul>
  <li class='col-left'><span class='print-label'>Degree</span><u><%= submission.degree_name %></u></li>
  <li class='col-right'><span class='print-label'>Major</span><u><%= submission.program_name %></u></li>
</ul>
<ul>
  <li class='col-left'><span class='print-label'>Advisor</span><u><%= CommitteeMember.advisor_name(submission) %></u></li>
</ul>
</div>

app/views/admin/submissions/print/signatory_page.html.erb
<div id='print-button' class="noprint"><a id="print_it" href="#">Print</a>
  <span class='status'>status-<%= submission.id%></span>
  <%= simple_form_for submission, url: admin_submissions_print_signatory_page_update_path(submission), html: { class: 'hidden', id: 'print-form-page', } do |f| %>
      <%= f.input :id, readonly: true %>
      <%= f.input :is_printed, html: {class: 'update_printed' }%>
      <%= f.submit html: { class: 'update-printed' }%>
  <% end %>
</div>
<div class='print-it'>

  <%= render partial: 'admin/submissions/print/signatory_page_top', locals: {submission: submission, author: author} %>
  <div class='double-under'>&nbsp;</div>
  <%= render partial: 'admin/submissions/print/signatory_page_bottom', locals: { submission: submission, author: author } %>
  <div>
     <br />
    <% 6.times do %>
        <div class="print-notes"><hr /></div>
    <% end %>
  </div>
</div>